### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by yukina3230** [hedgieinsocks/gnome-extension-lineup#3]
Hi @hedgieinsocks , GNOME 45 beta has been released, please port it to the new version.

This link might help: https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

Thank you.

**Comment by hedgieinsocks** [comment]
Hello @yukina3230, thank you for the heads-up, I'll definitely try to do so during this month

**Comment by hedgieinsocks** [comment]
@yukina3230 I've ported it and tested it on gnome os nightly, and it seems to work for me (tested with keepass indicator from https://extensions.gnome.org/extension/615/appindicator-support/ ), so you can give it a try ( https://github.com/hedgieinsocks/lineup/tree/gnome-45-port) or wait for the ego update later this month if all goes well

**Comment by yukina3230** [comment]
Thank you, I'm currently using Gnome 44 on Arch so I'll wait for the next update.
